### ISSUE TITLE
20210301 Can't build with Polly

### ISSUE THREAD

**Issue by kutemeikito** [kutemeikito/RastaMod69-Clang#1]
Compiling with CLANG
clang version 13.0.0
make[1]: Entering directory '/root/out-memer'
  GEN     ./Makefile
scripts/kconfig/conf  --silentoldconfig Kconfig
  CHK     include/config/kernel.release
Cannot use CONFIG_CC_STACKPROTECTOR_STRONG: -fstack-protector-strong not supported by compiler
make[1]: *** [/root/MiuiR/Makefile:1333: prepare-compiler-check] Error 1
make[1]: *** Waiting for unfinished jobs....
make[1]: Leaving directory '/root/out-memer'
make: *** [Makefile:146: sub-make] Error 2

you need to Disable Polly Optimizer for fix it ..

**Comment by Elcid016** [comment]
how i do this
